// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

import (
	"github.com/99designs/gqlgen/graphql"
)

type NewUser struct {
	FullName string `json:"fullName"`
	Email    string `json:"email"`
}

type Receipt struct {
	ID          string `json:"id"`
	ImageName   string `json:"imageName"`
	ImageURL    string `json:"imageUrl"`
	User        *User  `json:"user"`
	DateCreated string `json:"DateCreated"`
}

type ReceiptImage struct {
	UserID string          `json:"userId"`
	File   *graphql.Upload `json:"file"`
}

type ReceiptInternal struct {
	ID          string `json:"id"`
	ImageName   string `json:"imageName"`
	UserID      string `json:"userId"`
	DateCreated string `json:"DateCreated"`
}

type User struct {
	ID          string `json:"id"`
	FullName    string `json:"fullName"`
	Email       string `json:"email"`
	DateCreated string `json:"DateCreated"`
}
