// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type AuthPayload struct {
	Token string `json:"token"`
	User  *User  `json:"user"`
}

// Receipt type returned in query receipts and receipt
type Receipt struct {
	ID          string `json:"id"`
	ImageName   string `json:"imageName"`
	Description string `json:"description"`
	// image url of the uploaded/sacled receipt image,
	// to access the image a valia token is needed in the request header
	ImageURL    string `json:"imageUrl"`
	DateCreated string `json:"dateCreated"`
}

type ReceiptInternal struct {
	ID          string `json:"id"`
	ImageName   string `json:"imageName"`
	Description string `json:"description"`
	UserID      string `json:"userId"`
	DateCreated string `json:"dateCreated"`
}

type User struct {
	ID          string  `json:"id"`
	Username    string  `json:"username"`
	Password    *string `json:"password"`
	DateCreated string  `json:"DateCreated"`
}
