// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type AuthPayload struct {
	Token string `json:"token"`
	User  *User  `json:"user"`
}

type Receipt struct {
	ID          string `json:"id"`
	ImageName   string `json:"imageName"`
	Description string `json:"description"`
	ImageURL    string `json:"imageUrl"`
	DateCreated string `json:"DateCreated"`
}

type ReceiptInternal struct {
	ID          string `json:"id"`
	ImageName   string `json:"imageName"`
	Description string `json:"description"`
	UserID      string `json:"userId"`
	DateCreated string `json:"DateCreated"`
}

type User struct {
	ID          string  `json:"id"`
	Username    string  `json:"username"`
	Password    *string `json:"password"`
	DateCreated string  `json:"DateCreated"`
}
